spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

security:
  api:
    enabled: true

storage:
  secure: true

reconciliation:
  enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
