spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:file_upload}
    username: ${DB_USERNAME:file_app}
    password: ${DB_PASSWORD:root}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html

storage:
  endpoint: ${STORAGE_ENDPOINT:http://localhost:9000}
  access-key: ${STORAGE_ACCESS_KEY:minioadmin}
  secret-key: ${STORAGE_SECRET_KEY:minioadmin}
  bucket: ${STORAGE_BUCKET:file-uploads}
  secure: ${STORAGE_SECURE:false}